apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
        {{- if .Values.forceImageUpdate }}
        deploymentTime: "{{ now | unixEpoch }}"
        {{- end }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        env:
        - name: ALWAYS_WIN
          value: {{ .Values.env.ALWAYS_WIN | quote }}
        - name: ALWAYS_LOSE
          value: {{ .Values.env.ALWAYS_LOSE | quote }}
        - name: DATABASE_TYPE
          value: {{ .Values.database.type | quote }}
        - name: DATABASE_NAME
          value: {{ .Values.database.name | quote }}
        {{- if eq .Values.database.type "mongodb" }}
        - name: MONGODB_URI
          value: mongodb://{{ .Release.Name }}-mongodb:27017/{{ .Values.database.name }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}